#!/bin/bash

# Check if script is running with uid 0
if [ "$(id -u)" != 0 ]; then
  echo "This script must be run as root"
  exit
fi

THISFILE="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
THISDIR=$(dirname $THISFILE)

# copy files
cp $THISDIR/usr/sbin/temp-throttle /usr/sbin/temp-throttle
cp $THISDIR/etc/temp_throttle.conf /etc/temp_throttle.conf
cp $THISDIR/etc/init.d/temp-throttle /etc/init.d/temp-throttle

# enable on startup
update-rc.d temp-throttle defaults
